<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Semester</name>
   <tag></tag>
   <elementGuidId>9c47876f-c829-4c21-ab6b-862c2c0295c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form1']/div[4]/div/div/div[2]/div/div[2]/div/div/nav/ul/li[5]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.nav-item.dropdown.res-dis-nn.open > div.dropdown-menu.animated.zoomIn > a.nav-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Semester&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ea3e9861-1c78-492b-85b2-2c00734b487d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../HallTickets_SpecialExam_Student.aspx</value>
      <webElementGuid>10ade621-839f-4cc6-8e45-b9b6e3b52375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>c8dd55dd-0f0e-49de-b98d-9386ff49a216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>057cfdd0-cea2-4a48-9e0b-443a13050f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Semester</value>
      <webElementGuid>6831beab-5632-46e7-922e-627b8a84b0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[4]/div[1]/div[@class=&quot;all-content-wrapper&quot;]/div[@class=&quot;header-advance-area&quot;]/div[@class=&quot;header-top-area&quot;]/div[@class=&quot;mobile-menu-area&quot;]/div[@class=&quot;container mean-container&quot;]/div[@class=&quot;mean-bar&quot;]/nav[@class=&quot;mean-nav&quot;]/ul[@class=&quot;mobile-menu-nav&quot;]/li[@class=&quot;nav-item dropdown res-dis-nn open&quot;]/div[@class=&quot;dropdown-menu animated zoomIn&quot;]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>e7097b6e-88e5-42b2-8dcb-c17995a1f177</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[4]/div/div/div[2]/div/div[2]/div/div/nav/ul/li[5]/div/a</value>
      <webElementGuid>983ac709-8940-420e-9564-888d0cca4711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Semester')])[2]</value>
      <webElementGuid>afa3c9b9-c419-42f4-9970-c676243b448c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year End Exam Fee Receipt'])[2]/following::a[2]</value>
      <webElementGuid>7901d47b-6b38-47c2-b067-bda30a946867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Covid Special Exam'])[2]/following::a[3]</value>
      <webElementGuid>3de5ed2c-6eb5-486e-a43f-bc0219290751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year End'])[2]/preceding::a[1]</value>
      <webElementGuid>fb16202c-0dd5-4bde-a99c-1aae11fde608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '../HallTickets_SpecialExam_Student.aspx')])[2]</value>
      <webElementGuid>6e19028c-3a9c-46d9-ba79-8ea64a34bbdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[5]/div/a</value>
      <webElementGuid>19843756-9bae-4a5f-8873-a0db50eb5793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../HallTickets_SpecialExam_Student.aspx' and (text() = 'Semester' or . = 'Semester')]</value>
      <webElementGuid>cb7958a5-61ae-4bc1-b594-c247399a3bc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
