<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>042cd9fe-24ab-4a92-84e3-126e0aa7ec2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://www.andhrauniversity.edu.in/img/ach10.jpeg')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>img:nth-child(7)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1bffbdde-2773-4302-8662-488b28641486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.andhrauniversity.edu.in/img/ach10.jpeg</value>
      <webElementGuid>f9010a87-9ef8-4b61-8beb-0eec7564c6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;page-content&quot;]/div[@class=&quot;container&quot;]/ul[@class=&quot;news&quot;]/img[2]</value>
      <webElementGuid>88e9ab1a-6a22-4fa5-8679-2e0fad0e3a51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.andhrauniversity.edu.in/img/ach10.jpeg')]</value>
      <webElementGuid>a057440a-1a70-4742-8b4c-5a568678445d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>e1094341-39a3-453c-8e3e-4772fbe75335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.andhrauniversity.edu.in/img/ach10.jpeg']</value>
      <webElementGuid>ab018a17-e351-42ea-a56e-e8244f82d4b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
