<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__fas fa-bars</name>
   <tag></tag>
   <elementGuidId>a438cd9b-48bb-4055-9b00-1ea1dc0a6768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='menu']/div/nav/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fas.fa-bars</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>274c8ca5-4b44-4512-a039-8a45c5a8ed9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-bars</value>
      <webElementGuid>3a7140a6-76dc-4762-b1b8-0e22f9d8dea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;container&quot;]/nav[@class=&quot;navbar navbar-expand-lg&quot;]/button[@class=&quot;navbar-toggler p-0 border-0&quot;]/span[@class=&quot;fas fa-bars&quot;]</value>
      <webElementGuid>edf7c016-f5ae-4419-ad14-3b812b084ae2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='menu']/div/nav/button/span</value>
      <webElementGuid>60c526c9-9797-44c2-860f-9c9a0380034b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>491e18eb-5fdd-4f48-8790-4133c9bffd20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
