<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AUCMS</name>
   <tag></tag>
   <elementGuidId>d77725f4-5e29-43f5-b605-601c0a784bf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'AUCMS')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;AUCMS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>02502f22-00ac-4248-aa7f-3f0ff712b829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://auerp.andhrauniversity.edu.in/aucms/</value>
      <webElementGuid>75ea62d4-2c4f-4428-a7cf-ff8b269794b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>blank</value>
      <webElementGuid>038e21c5-4f4f-4905-af1e-bfa0eafa8e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AUCMS </value>
      <webElementGuid>ae54c2c7-eebf-411e-b237-49fb1b8c75c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row row-eq-height&quot;]/div[@class=&quot;col-xl-3 col-md-12&quot;]/div[@class=&quot;quick-links&quot;]/ul[1]/li[@class=&quot;w3-small&quot;]/a[1]</value>
      <webElementGuid>8a9eaa9a-4604-4d74-9192-098949f42d96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AUCMS')]</value>
      <webElementGuid>ce2fce1f-b195-4a2a-b63c-5e4f79b89bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AU LMS(MOOCs)'])[1]/following::a[1]</value>
      <webElementGuid>61ea9970-d5d3-4f8b-980e-9f0def01ea62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PG &amp; Professional Syllabus'])[1]/following::a[2]</value>
      <webElementGuid>9c344b3a-82c0-432b-a606-14e68e1fd791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply for Certificates'])[1]/preceding::a[1]</value>
      <webElementGuid>c0d1b0d4-2e10-4e48-b29d-2406c48a0d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply for Revaluation'])[1]/preceding::a[2]</value>
      <webElementGuid>8a3fcacf-675a-4a08-a01a-0fc2740acc5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AUCMS']/parent::*</value>
      <webElementGuid>02b7c82c-b0f0-4d51-9a13-3d994f8deedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://auerp.andhrauniversity.edu.in/aucms/']</value>
      <webElementGuid>6a237868-9245-417d-8219-fb5e0f14b951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[9]/a</value>
      <webElementGuid>89523aca-a107-4a74-a45f-cef05a8d9acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://auerp.andhrauniversity.edu.in/aucms/' and (text() = 'AUCMS ' or . = 'AUCMS ')]</value>
      <webElementGuid>1ce4da3a-52a0-4ba8-b68d-3df4ea5330d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
